export const USER = {
  name: 'Akash Sharma',
  firstName: 'Akash',
  phone: '+91 98765 43210',
  email: 'akash.sharma@email.com',
  city: 'Agra',
  state: 'Uttar Pradesh',
  avatar: null,
  memberSince: 'Jan 2024',
  totalWashes: 14,
  loyaltyPoints: 420,
} as const;

export const VEHICLE = {
  make: 'Hyundai',
  model: 'i20',
  plate: 'UP80 AB 1234',
  color: 'Pearl White',
  year: '2022',
  type: 'Hatchback',
} as const;

export const SERVICES = [
  {
    id: 'basic',
    name: 'Basic Wash',
    tagline: 'Quick exterior rinse & dry',
    price: 299,
    duration: 45,
    icon: '💧',
    color: ['#06B6D4', '#22D3EE'] as string[],
    features: ['Exterior wash', 'Rinse & dry', 'Tyre clean'],
    popular: false,
  },
  {
    id: 'premium',
    name: 'Premium Wash',
    tagline: 'Deep clean with wax shine',
    price: 499,
    duration: 60,
    icon: '✨',
    color: ['#1A56DB', '#06B6D4'] as string[],
    features: ['All Basic features', 'Foam wash', 'Wax polish', 'Dashboard wipe'],
    popular: true,
  },
  {
    id: 'interior',
    name: 'Interior Cleaning',
    tagline: 'Full interior vacuum & wipe',
    price: 699,
    duration: 75,
    icon: '🪑',
    color: ['#7C3AED', '#A78BFA'] as string[],
    features: ['Vacuum seats', 'Dashboard clean', 'Glass clean', 'Air freshener'],
    popular: false,
  },
  {
    id: 'detailing',
    name: 'Full Detailing',
    tagline: 'Complete inside-out detailing',
    price: 999,
    duration: 120,
    icon: '🏆',
    color: ['#059669', '#10B981'] as string[],
    features: ['All Premium', 'All Interior', 'Engine bay', 'Ceramic coat'],
    popular: false,
  },
] as const;

export const BOOKINGS = [
  {
    id: 'B001',
    service: 'Premium Wash',
    price: 499,
    date: 'Today, 10:30 AM',
    dateShort: 'Jun 8',
    vehicle: 'Hyundai i20 · UP80 AB 1234',
    status: 'upcoming',
    washer: 'Ravi Kumar',
    washerRating: 4.8,
    address: '12, Fatehabad Road, Agra',
  },
  {
    id: 'B002',
    service: 'Full Detailing',
    price: 999,
    date: 'Jun 5, 2:00 PM',
    dateShort: 'Jun 5',
    vehicle: 'Hyundai i20 · UP80 AB 1234',
    status: 'completed',
    washer: 'Suresh Singh',
    washerRating: 4.9,
    address: '12, Fatehabad Road, Agra',
    rating: 5,
  },
  {
    id: 'B003',
    service: 'Basic Wash',
    price: 299,
    date: 'Jun 1, 9:00 AM',
    dateShort: 'Jun 1',
    vehicle: 'Hyundai i20 · UP80 AB 1234',
    status: 'completed',
    washer: 'Manoj Verma',
    washerRating: 4.7,
    address: '12, Fatehabad Road, Agra',
    rating: 4,
  },
  {
    id: 'B004',
    service: 'Interior Cleaning',
    price: 699,
    date: 'May 28, 11:00 AM',
    dateShort: 'May 28',
    vehicle: 'Hyundai i20 · UP80 AB 1234',
    status: 'cancelled',
    washer: null,
    washerRating: null,
    address: '12, Fatehabad Road, Agra',
    rating: null,
  },
] as const;
